stages:
  - deploy

deploy_to_vps:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache sshpass openssh
  script:
    - sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "
        cd /var/www/projet &&
        git pull &&
        docker-compose pull &&
        docker-compose up -d --remove-orphans
      "
  only:
    - main
    - test-deploiement
