stages:
  - deploy

deploy_to_vps:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache sshpass openssh

    - |
      echo "DEBUG: Test ping du VPS"
      ping -c 3 $VPS_HOST || echo "Ping failed"
      echo "DEBUG: Test SSH avec sshpass"
      sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 $VPS_USER@$VPS_HOST 

  script:
    - sshpass -p $VPS_PASSWORD ssh $VPS_USER@$VPS_HOST "
        cd /srv/reseau_social_ville &&
        git pull &&
        docker compose pull &&
        docker compose up -d --remove-orphans
      "
  only:
    - main
    - test-deploiement
